name: Nix Chore
description: "GitHub Actions to help checking Nix Flake Repo"
inputs:
  nu-script:  # id of input
    description: "Nushell Script to run"
    required: true
    default: "update.nu"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: hustcer/setup-nu@v3
    - id: check
      shell: nu {0}
      run: |
        nu ${{ inputs.nu-script }};
        let report = (git status --porcelain);
        $"report=($report)" | save --append $env.GITHUB_OUTPUT;
    - id: cpr
      name: Create Pull Request (if changed)
      uses: peter-evans/create-pull-request@v7
      with:
        branch: "changes/nix-flake"
        commit-message: |
          [CI-generated] changes detected

          ${{ steps.check.outputs.report }}
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      shell: bash
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
